#!/usr/bin/env python3
"""Build a Mermaid MQTT topic map from every service's get_mqtt_description().

Each ZMW service *owns* one MQTT topic (its ``svc_topic``) and talks to others,
declared in get_mqtt_description() as ``reads_mqtt_topic`` (topics it subscribes
to) and ``writes_mqtt_topic`` (topics it publishes commands/state into). This
script reads those facts from every zmw_* service and renders a single Mermaid
``flowchart`` of which topics live on the broker and which way messages travel
between them.

The read/write split matters: a service reading zmw_shelly_plug is drawn as
shelly -> sensormon, while a service publishing a tts command into
zmw_speaker_announce is drawn the other way. Both are "dependencies", but the
data flows in opposite directions.

The diagram is injected into the top-level README.md between the markers:

    <!-- BEGIN MQTT MAP (auto-generated by scripts/build_mqtt_map.py) -->
    <!-- END MQTT MAP -->

so it survives the truncate+append performed by scripts/update_readme.sh (the
markers live above the "# Supported Services" separator line).

Usage:
    python scripts/build_mqtt_map.py            # regenerate the map in README.md
    python scripts/build_mqtt_map.py --print     # print the map, don't touch README
"""
import os
import sys

# Reuse the AST helpers already used to render the per-service MQTT sections.
from update_readme_mqtt import extract_mqtt_description, get_svc_topic

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

BEGIN_MARKER = "<!-- BEGIN MQTT MAP (auto-generated by scripts/build_mqtt_map.py) -->"
END_MARKER = "<!-- END MQTT MAP -->"

# Topics produced by something other than a ZMW service (eg the Zigbee2MQTT daemon).
# Anything a service depends on that isn't owned by a discovered service is treated
# as external and rendered with a distinct shape.
EXTERNAL_TOPIC_LABELS = {
    "zigbee2mqtt": "zigbee2mqtt<br/><i>Zigbee2MQTT daemon</i>",
}

# Commands every service exposes by convention to describe/diagnose *itself*. They
# say nothing about the home, so a topic offering only these has no useful interface.
INTROSPECTION_COMMANDS = {"get_mqtt_description", "get_stats"}


def _svc_display_name(svc_dir_name):
    """zmw_cat_snack_dispenser -> ZmwCatSnackDispenser."""
    return "".join(part.capitalize() for part in svc_dir_name.split("_"))


def collect_services():
    """Return list of {dir, name, owns, depends} for every service that declares a topic."""
    svcs = []
    for d in sorted(os.listdir(PROJECT_DIR)):
        svc_dir = os.path.join(PROJECT_DIR, d)
        if not (d.startswith("zmw_") and os.path.isdir(svc_dir)):
            continue
        py_path = os.path.join(svc_dir, f"{d}.py")
        if not os.path.isfile(py_path):
            continue

        desc = extract_mqtt_description(py_path)
        if desc is None:
            # Aggregator/monitor services (Dashboard, Servicemon, Assistant) don't
            # expose a service interface; they subscribe broadly and are omitted.
            continue

        owns = get_svc_topic(py_path)
        if owns is None:
            continue

        cmds = desc.get("commands") or {}
        anns = desc.get("announcements") or {}
        svcs.append({
            "dir": d,
            "name": _svc_display_name(d),
            "owns": owns,
            # Topics we subscribe to (data flows IN to us) and topics we publish
            # commands/state into (data flows OUT of us). A topic in both is a
            # two-way conversation and is drawn as a single bidirectional edge.
            "reads": list(desc.get("reads_mqtt_topic") or []),
            "writes": list(desc.get("writes_mqtt_topic") or []),
            # Commands worth calling: anything that isn't pure self-introspection.
            "actionable": [c for c in cmds if c not in INTROSPECTION_COMMANDS],
            # Announcements worth subscribing to. A "<cmd>_reply" is just the echo of
            # a request, so it carries no state a subscriber couldn't have asked for;
            # only unsolicited events (on_motion_detected, client_joined, ...) count.
            "events": [a for a in anns if not a.endswith("_reply")],
        })
    return svcs


def mark_passive_services(svcs):
    """Flag services whose own topic offers nothing to talk to.

    A topic is worth knowing about if you can *send* it something (an actionable
    command), *learn* something from it (an unsolicited event), or if some other
    service already reads it. A service failing all three still exists on the
    broker, but only as a consumer -- there is no reason to publish to its topic.
    """
    inbound = set()
    for s in svcs:
        inbound.update(s["reads"])
        inbound.update(s["writes"])

    for s in svcs:
        s["passive"] = not (s["actionable"] or s["events"] or s["owns"] in inbound)
    return svcs


def build_mermaid(svcs):
    owned_topics = {s["owns"] for s in svcs}

    # Any topic we talk to but nobody owns is produced by something outside ZMW.
    external_topics = set()
    for s in svcs:
        for t in s["reads"] + s["writes"]:
            if t not in owned_topics:
                external_topics.add(t)

    lines = ["```mermaid", "flowchart LR"]

    # Service nodes: one per owned topic. Label shows the service and the topic it owns.
    for s in svcs:
        if s["passive"]:
            lines.append(
                f'    {s["owns"]}["{s["name"]}<br/><i>no public interface</i>"]')
        else:
            lines.append(f'    {s["owns"]}["{s["name"]}<br/><code>{s["owns"]}</code>"]')

    # External topic nodes (stadium shape).
    for t in sorted(external_topics):
        label = EXTERNAL_TOPIC_LABELS.get(t, t)
        lines.append(f'    {t}(["{label}"])')

    lines.append("")

    # Edges follow the messages: an arrow points from publisher to subscriber.
    # Reading a topic is an inbound arrow; publishing into one is outbound; doing
    # both collapses into a single bidirectional edge rather than two arrows.
    # Passive services still talk, so keep their edges, dotted to match the node.
    for s in svcs:
        reads, writes = set(s["reads"]), set(s["writes"])
        for t in sorted(reads | writes):
            if t in reads and t in writes:
                arrow = "<-.->" if s["passive"] else "<-->"
                lines.append(f"    {s['owns']} {arrow} {t}")
            elif t in reads:
                arrow = "-.->" if s["passive"] else "-->"
                lines.append(f"    {t} {arrow} {s['owns']}")
            else:
                arrow = "-.->" if s["passive"] else "-->"
                lines.append(f"    {s['owns']} {arrow} {t}")

    lines.append("")
    # Style external topics and passive services distinctly.
    passive = [s["owns"] for s in svcs if s["passive"]]
    for t in sorted(external_topics):
        lines.append(f"    class {t} external;")
    for t in sorted(passive):
        lines.append(f"    class {t} passive;")
    if external_topics:
        lines.append("    classDef external fill:#fde68a,stroke:#b45309,color:#111;")
    if passive:
        lines.append(
            "    classDef passive fill:#e5e7eb,stroke:#9ca3af,color:#6b7280,"
            "stroke-dasharray:4 3;")

    lines.append("```")
    return "\n".join(lines)


def build_section(svcs):
    """Full README section (heading + explanation + mermaid) between the markers."""
    body = [
        BEGIN_MARKER,
        "",
        "The diagram below is generated from every service's `get_mqtt_description()`:",
        "`svc_topic` for the topic each service owns, plus `reads_mqtt_topic` and",
        "`writes_mqtt_topic` for the topics it talks to.",
        "",
        "**Arrows follow the messages.** `A --> B` means *A publishes and B subscribes*,",
        "so the arrow points the way the data travels. A service that both reads a topic",
        "and publishes into it gets one bidirectional `<-->` edge. Each node is labelled",
        "with the service and the single topic it owns; external (non-ZMW) producers such",
        "as the Zigbee2MQTT daemon are shown with a rounded shape.",
        "",
        "Pure aggregator services (ZmwDashboard, ZmwServicemon, ZmwAssistant) subscribe",
        "to most/all topics and are omitted here to keep the map readable.",
        "",
        "Greyed-out, dashed nodes own a topic with **no useful interface**: every",
        "command they expose is self-introspection (`get_mqtt_description`, `get_stats`),",
        "they publish no unsolicited events, and no other service reads them. They still",
        "run and still consume other topics -- there is just no reason to publish to",
        "theirs.",
        "",
        build_mermaid(svcs),
        "",
        END_MARKER,
    ]
    return "\n".join(body)


def inject_into_readme(section):
    readme_path = os.path.join(PROJECT_DIR, "README.md")
    with open(readme_path) as f:
        content = f.read()

    start = content.find(BEGIN_MARKER)
    end = content.find(END_MARKER)
    if start == -1 or end == -1:
        raise SystemExit(
            f"ERROR: MQTT map markers not found in {readme_path}. "
            f"Add a section containing:\n{BEGIN_MARKER}\n{END_MARKER}"
        )
    end += len(END_MARKER)
    new_content = content[:start] + section + content[end:]

    with open(readme_path, "w") as f:
        f.write(new_content)
    print(f"Updated MQTT map in {readme_path} ({len(section.splitlines())} lines)")


def main():
    svcs = mark_passive_services(collect_services())
    section = build_section(svcs)
    if "--print" in sys.argv[1:]:
        print(section)
        return
    inject_into_readme(section)


if __name__ == "__main__":
    main()
